import { detectIntent, INTENTS } from '../routes/chat';

describe('Intent detection', () => {
    const testCases = {
        ADD_TASK: [
            'Add a task to finish the report by next Monday',
            'Add a task to call mom',
            'Create a new task to buy groceries',
            'I want to add a task to submit the assignment',
            'Schedule a task for cleaning the garage',
            'Please add a task to pay the bills',
            'Can you add a task to pick up the kids?',
            'I need to add a task for meeting John at 3 PM',
            'Put a task on my list to read a book',
            'Add a new task: plan the vacation',
            'Remind me to add a task for dentist appointment',
            'Add a task for sending the email to the client',
            'Create a task to workout at 6 AM',
            'Add task to water the plants',
            'I want to create a task for grocery shopping tomorrow',
            'Can you schedule a task for finishing the project report?',
            'Add a task: call the bank',
            'Add task for picking up the dry cleaning',
            'Create a new task: organize the files',
            'Please schedule a task to walk the dog',
        ],
        LIST_TASKS: [
            'Show me all my tasks',
            'List all tasks for today',
            'What tasks do I have?',
            'Display my to-do list',
            'Can you list my tasks?',
            'I want to see my tasks',
            'Give me a list of tasks',
            'Show tasks due this week',
            'List my pending tasks',
            'What are my tasks for tomorrow?',
            'Can I see my task list?',
            'Display tasks for this month',
            'List all incomplete tasks',
            'Show upcoming tasks',
            'What tasks are on my agenda?',
            'Give me today’s tasks',
            'Show me tasks by priority',
            'List tasks assigned to me',
            'Display urgent tasks',
            'What are my scheduled tasks?',
        ],
        DELETE_TASK: [
            'Delete my task to call mom',
            'Remove the grocery shopping task',
            'Can you delete task for meeting John?',
            'Erase the task for dentist appointment',
            'Delete task number 5',
            'Remove my to-do for cleaning garage',
            'Please delete the workout task',
            'Delete task: submit assignment',
            'Cancel my task to pay bills',
            'Delete the task to walk the dog',
            'Remove the task I added yesterday',
            'Erase the task about reading book',
            'Delete my scheduled tasks for today',
            'Can you remove tasks marked done?',
            'Delete tasks due tomorrow',
            'Delete all completed tasks',
            'Remove the task I just created',
            'Cancel task for checking emails',
            'Erase task for project deadline',
            'Delete the task called plan vacation',
        ],
        REFLECT_JOURNAL: [
            'I want to reflect on my day',
            'Journal my thoughts',
            'Can I write a reflection?',
            'Help me with my daily reflection',
            'Add a journal entry',
            'Reflect on today’s events',
            'I need to record my thoughts',
            'Write a journal for me',
            'Start a reflection for today',
            'Can you log my reflection?',
            'Create a new journal entry',
            'I want to note my feelings',
            'Help me reflect on yesterday',
            'Journal my mood today',
            'Add reflections about work',
            'Record my personal thoughts',
            'Reflect on my achievements',
            'Write down what I learned today',
            'I want to analyze my day',
            'Log my daily reflection',
        ],
        SMALLTALK: [
            'Hello!',
            'How are you?',
            'What’s up?',
            'Good morning!',
            'Hi there',
            'How’s your day going?',
            'Tell me a joke',
            'Good evening',
            'Hey!',
            'How’s it going?',
            'Nice to meet you',
            'What are you doing?',
            'Hi, how are things?',
            'Greetings!',
            'How’s life?',
            'Tell me something interesting',
            'Hey, what’s new?',
            'Good afternoon!',
            'How’s your mood today?',
            'What’s happening?',
        ],
        SUMMARIES: [
            'Summarize my day',
            'Give me a summary of my meetings',
            'Summarize my tasks',
            'Can you give me a summary?',
            'Summarize my journal entries',
            'Provide a summary of work done',
            'Summarize the conversation',
            'Give me a summary report',
            'Summarize today’s events',
            'Summarize my emails',
            'Can you summarize my notes?',
            'Provide a daily summary',
            'Summarize key points',
            'Give me a summary of projects',
            'Summarize last week’s tasks',
            'Provide a summary of goals achieved',
            'Summarize my learning today',
            'Summarize the document',
            'Give me an overview of tasks',
            'Provide a summary for tomorrow',
        ],
        PERFORMANCE_INSIGHTS: [
            'Give me performance insights',
            'How am I performing?',
            'Provide insights on my productivity',
            'Analyze my work performance',
            'Show me performance metrics',
            'I want feedback on performance',
            'Assess my productivity',
            'Provide insights on my goals',
            'Analyze daily performance',
            'Performance report, please',
            'How efficient am I?',
            'Show work efficiency insights',
            'Track my performance today',
            'Give me productivity stats',
            'Evaluate my recent work',
            'Show me performance trends',
            'Analyze my task completion rate',
            'Provide feedback on achievements',
            'Give insights on my progress',
            'Evaluate my weekly performance',
        ],
        LONG_CONVERSATION_ANALYSIS: [
            'Analyze my long conversation',
            'Provide insights from my chat',
            'Summarize this conversation',
            'Analyze conversation trends',
            'Give me conversation analytics',
            'Can you break down the conversation?',
            'Analyze the chat history',
            'Provide conversation report',
            'Extract insights from conversation',
            'Show patterns in my chats',
            'Review my discussion',
            'Analyze messages from last week',
            'Summarize chat interactions',
            'Provide long conversation analysis',
            'Give feedback on conversation flow',
            'Analyze communication style',
            'Provide insights from team chat',
            'Analyze meeting conversation',
            'Give me conversation highlights',
            'Review conversation for key points',
        ],
    };

    Object.entries(testCases).forEach(([intent, phrases]) => {
        describe(`detect${intent}Intent`, () => {
            phrases.forEach((phrase, index) => {
                test(`variation ${index + 1}`, async () => {
                    const result = await detectIntent(phrase);
                    expect(result).toBe(INTENTS[intent as keyof typeof INTENTS]);
                });
            });
        });
    });
});
